AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket for static website hosting.
  ACMCertificateArn:
    Type: String
    Description: The ARN of the ACM certificate for the CloudFront distribution.
  HostedZoneId:
    Type: String
    Description: The ID of the Route 53 hosted zone.
  CloudFrontHostedZoneId:
    Type: String
    Description: The Hosted Zone ID for CloudFront alias record.
    Default: Z2FDTNDATAQYW2
  Environment:
    Type: String
    Default: "dev"
    Description: "The environment for the deployment (dev or prod)."
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  CreateDNSRecords:
    Type: String
    Default: "true"
    Description: "Set to 'true' to create Route 53 DNS records. Set to 'false' to skip."
    AllowedValues:
      - "true"
      - "false"
  CloudFrontKey:
    Type: String
    Description: The public key for the development website base 64 encoded.

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: true

  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-backup-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldBackups
            Status: Enabled
            ExpirationInDays: 30
            Prefix: ""

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "CloudFront Origin Access Identity for 100 Letters Project - ${Environment}"

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${BucketName}-${Environment}/*"

  StaticWebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "CloudFront Distribution for 100 Letters Project - ${Environment}"
        Enabled: true
        Origins:
          - Id: "S3Origin"
            DomainName: !GetAtt StaticWebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          CachePolicyId: !Ref DefaultCachePolicy  # Use a Cache Policy
          ViewerProtocolPolicy: "redirect-to-https"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
            Headers:
              - "Host"  # Forward Host header
          AllowedMethods:
            - GET
            - HEAD
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: "arn:aws:cloudfront::771265364914:function/auth-at-edge-dev/4"
        CacheBehaviors:
          - PathPattern: "*"
            TargetOriginId: "S3Origin"
            ViewerProtocolPolicy: "redirect-to-https"
            CachePolicyId: !Ref QueryStringCachePolicy  # Use Cache Policy for query strings
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: "all"
              Headers:
                - "Host"
            FunctionAssociations:
              - EventType: viewer-request
                FunctionARN: "arn:aws:cloudfront::771265364914:function/auth-at-edge-dev/4"
        DefaultRootObject: "index.html"
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          SslSupportMethod: "sni-only"
        Aliases:
          - !If 
            - IsProd
            - "onehundredletters.com"
            - "dev.onehundredletters.com"
          - !If 
            - IsProd
            - "www.onehundredletters.com"
            - "www.dev.onehundredletters.com"

  Route53RootRecordSet:
    Condition: CreateDNSRecordsCondition
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If 
        - IsProd
        - "onehundredletters.com."
        - "dev.onehundredletters.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt StaticWebsiteCloudFront.DomainName
        HostedZoneId: !Ref CloudFrontHostedZoneId

  Route53WWWRecordSet:
    Condition: CreateDNSRecordsCondition
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If 
        - IsProd
        - "www.onehundredletters.com."
        - "www.dev.onehundredletters.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt StaticWebsiteCloudFront.DomainName
        HostedZoneId: !Ref CloudFrontHostedZoneId
  
  CloudFrontPublicKey:
    Type: AWS::CloudFront::PublicKey
    Properties:
      PublicKeyConfig:
        CallerReference: !Sub "PublicKey-${Environment}"
        Name: !Sub "PublicKey-${Environment}"
        EncodedKey: !Ref CloudFrontKey
        Comment: "Public key for signed cookies"

  CloudFrontKeyGroup:
    Type: AWS::CloudFront::KeyGroup
    Properties:
      KeyGroupConfig:
        Name: !Sub "KeyGroup-${Environment}"
        Items:
          - !Ref CloudFrontPublicKey
        Comment: "Key group for signed cookies"

  # Cache Policy for Default Cache Behavior (no query string forwarding)
  DefaultCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "DefaultCachePolicy-${Environment}"
        Comment: !Sub "Cache Policy for Default Cache Behavior - ${Environment}"
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  # Cache Policy for Query String Cache Behavior (forward query strings)
  QueryStringCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "QueryStringCachePolicy-${Environment}"
        Comment: !Sub "Cache Policy for Query String Cache Behavior - ${Environment}"
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          CookiesConfig:
            CookieBehavior: all
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod" ]
  CreateDNSRecordsCondition: !Equals [ !Ref CreateDNSRecords, "true" ]
