AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket for static website hosting.
  ACMCertificateArn:
    Type: String
    Description: The ARN of the ACM certificate for the CloudFront distribution.
  HostedZoneId:
    Type: String
    Description: The ID of the Route 53 hosted zone.
  CloudFrontHostedZoneId:
    Type: String
    Description: The Hosted Zone ID for CloudFront alias record.
    Default: Z2FDTNDATAQYW2
  Environment:
    Type: String
    Default: "dev"
    Description: "The environment for the deployment (dev or prod)."
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  CreateDNSRecords:
    Type: String
    Default: "true"
    Description: "Set to 'true' to create Route 53 DNS records. Set to 'false' to skip."
    AllowedValues:
      - "true"
      - "false"
  CloudFrontKey:
    Type: String
    Description: The public key for the development website base 64 encoded.
  EnableSignedCookiesCheck:
    Type: String
    Default: "true"
    Description: "Set to 'true' to enable signed cookies check, 'false' to disable."
    AllowedValues:
      - "true"
      - "false"
  CloudFrontKeyGroupId:
    Type: String
    Description: "The ID of an existing CloudFront Key Group to use for signed cookies."
    Default: ""

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: true

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-images-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - '*'
            ExposedHeaders:
              - ETag
            MaxAge: 3000
            AllowedOrigins: !If
              - IsProd
              - 
                - "https://www.onehundredletters.com"
                - "https://onehundredletters.com"
              - 
                - "http://localhost:3000"
                - "http://localhost:8080"
                - "https://www.dev.onehundredletters.com"
                - "https://dev.onehundredletters.com"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: unprocessed/
            Function: !ImportValue 
              Fn::Sub: "image-processor-lambda-arn-${Environment}"

  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-backup-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldBackups
            Status: Enabled
            ExpirationInDays: 30
            Prefix: ""

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "CloudFront Origin Access Identity for 100 Letters Project - ${Environment}"

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${BucketName}-${Environment}/*"

  ImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${BucketName}-images-${Environment}/*"

  CloudFrontKeyGroup:
    Type: AWS::CloudFront::KeyGroup
    Properties:
      KeyGroupConfig:
        Name: !Sub "KeyGroup-for-${Environment}"
        Items:
          - !Ref CloudFrontPublicKey

  CloudFrontPublicKey:
    Type: AWS::CloudFront::PublicKey
    Properties:
      PublicKeyConfig:
        CallerReference: !Sub "PublicKey-${Environment}"
        Name: !Sub "PublicKey-${Environment}"
        EncodedKey: !Ref CloudFrontKey
        Comment: "Public key for signed cookies"

  StaticWebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "CloudFront Distribution for 100 Letters Project - ${Environment}"
        Enabled: true
        Origins:
          - Id: "S3Origin"
            DomainName: !GetAtt StaticWebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
          - Id: "ImageS3Origin"
            DomainName: !GetAtt ImageBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
          TrustedKeyGroups:
            Fn::If:
              - EnableSignedCookiesCheckCondition
              - [ !Ref CloudFrontKeyGroupId ]
              - !Ref "AWS::NoValue"
          AllowedMethods:
            - GET
            - HEAD
        CacheBehaviors:
          - PathPattern: "/images/*"
            TargetOriginId: "ImageS3Origin"
            ViewerProtocolPolicy: "redirect-to-https"
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: "none"
        DefaultRootObject: "index.html"
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          SslSupportMethod: "sni-only"
        Aliases:
          - !If 
            - IsProd
            - "onehundredletters.com"
            - "dev.onehundredletters.com"
          - !If 
            - IsProd
            - "www.onehundredletters.com"
            - "www.dev.onehundredletters.com"
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: "/403.html"
            ResponseCode: 200
            ErrorCachingMinTTL: 0

  Route53RootRecordSet:
    Condition: CreateDNSRecordsCondition
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If 
        - IsProd
        - "onehundredletters.com."
        - "dev.onehundredletters.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt StaticWebsiteCloudFront.DomainName
        HostedZoneId: !Ref CloudFrontHostedZoneId

  Route53WWWRecordSet:
    Condition: CreateDNSRecordsCondition
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If 
        - IsProd
        - "www.onehundredletters.com."
        - "www.dev.onehundredletters.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt StaticWebsiteCloudFront.DomainName
        HostedZoneId: !Ref CloudFrontHostedZoneId

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod" ]
  EnableSignedCookiesCheckCondition: !Equals [ !Ref EnableSignedCookiesCheck, "true" ]
  CreateDNSRecordsCondition: !Equals [ !Ref CreateDNSRecords, "true" ]
