name: Rollback S3 Deployment

on:
  workflow_dispatch:
    inputs:
      backup_s3_key:
        description: 'S3 Key for the backup to restore e.g. 20250225083000'
        required: true
        type: string

jobs:
  rollback:
    name: Revert S3 Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Restore Selected Backup
        run: |
          echo "Rolling back to ${{ inputs.backup_s3_key }}..."
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET_BACKUP }}/${{ inputs.backup_s3_key }}/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_BUCKET_BACKUP: ${{ secrets.AWS_S3_BUCKET_BACKUP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
